import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
} from 'chart.js'
import { Bar } from 'react-chartjs-2'
import type { EnergySource } from '../data/dashboardMock'
import { SimulationCard, SimulationStatusBadge } from '@/shared/components'

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend)

interface EnergyBarChartProps {
  data: EnergySource[]
}

export function EnergyBarChart({ data }: EnergyBarChartProps) {
  const total = data.reduce((sum, s) => sum + s.kwh, 0)
  const totalFormatted = total.toLocaleString('en-US')
  const styles = typeof window !== 'undefined' ? getComputedStyle(document.documentElement) : null
  const chart3 = styles?.getPropertyValue('--chart-3').trim() || 'rgba(29,201,98,0.45)'
  const chart4 = styles?.getPropertyValue('--chart-4').trim() || 'rgba(29,201,98,0.25)'

  const chartData = {
    labels: data.map((s) => s.label),
    datasets: [
      {
        label: 'kWh',
        data: data.map((s) => s.kwh),
        backgroundColor: chart4,
        borderColor: chart3,
        borderWidth: 2,
        borderRadius: 6,
        hoverBackgroundColor: chart3,
      },
    ],
  }

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        callbacks: {
          label: (ctx: { parsed: { y: number } }) =>
            `${ctx.parsed.y.toLocaleString('en-US')} kWh`,
        },
      },
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { color: '#64748b', font: { family: 'Manrope', size: 12 } },
      },
      y: {
        grid: { color: 'rgba(15,23,42,0.08)' },
        ticks: {
          color: '#64748b',
          font: { family: 'Manrope', size: 11 },
          callback: (value: number | string) => `${Number(value) / 1000}k`,
        },
      },
    },
  }

  return (
    <SimulationCard className="flex h-full flex-col">
      <div className="mb-2 flex items-start justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-content-dark/70">
            Energy Generated by Source
          </p>
          <p className="mt-1 text-xl font-extrabold text-slate-900 dark:text-content-dark lg:text-2xl">
            {totalFormatted} kWh
          </p>
        </div>
        <SimulationStatusBadge icon={<span className="material-symbols-outlined text-base">trending_up</span>}>
          +10%
        </SimulationStatusBadge>
      </div>
      <div className="min-h-[118px] flex-1 lg:min-h-[132px]" role="img" aria-label="Energy generated by source">
        <Bar data={chartData} options={options as never} />
      </div>
    </SimulationCard>
  )
}
