import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Tooltip,
  Legend,
} from 'chart.js'
import { Bar } from 'react-chartjs-2'
import type { EnergySource } from '../data/dashboardMock'
import { formatKwh, formatKwhAxisTick } from '../services/dashboardFormatters'
import { SimulationCard, SimulationStatusBadge } from '@/shared/components'

ChartJS.register(CategoryScale, LinearScale, BarElement, Tooltip, Legend)

interface EnergyBarChartProps {
  data: EnergySource[]
}

export function EnergyBarChart({ data }: EnergyBarChartProps) {
  const total = data.reduce((sum, s) => sum + s.kwh, 0)
  const styles = typeof window !== 'undefined' ? getComputedStyle(document.documentElement) : null
  const chart3 = styles?.getPropertyValue('--chart-3').trim() || 'rgba(29,201,98,0.45)'
  const chart4 = styles?.getPropertyValue('--chart-4').trim() || 'rgba(29,201,98,0.25)'

  const chartData = {
    labels: data.map((s) => s.label),
    datasets: [
      {
        label: 'kWh',
        data: data.map((s) => s.kwh),
        backgroundColor: chart4,
        borderColor: chart3,
        borderWidth: 2,
        borderRadius: 6,
        hoverBackgroundColor: chart3,
      },
    ],
  }

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        callbacks: {
          label: (ctx: { parsed: { y: number } }) =>
            formatKwh(ctx.parsed.y),
        },
      },
    },
    scales: {
      x: {
        grid: { display: false },
        ticks: { color: '#64748b', font: { family: 'Manrope', size: 12 } },
      },
      y: {
        grid: { color: 'rgba(15,23,42,0.08)' },
        ticks: {
          color: '#64748b',
          font: { family: 'Manrope', size: 11 },
          callback: (value: number | string) => formatKwhAxisTick(Number(value)),
        },
      },
    },
  }

  return (
    <SimulationCard className="flex h-full min-h-0 flex-col overflow-hidden">
      <div className="mb-2.5 flex items-start justify-between gap-4">
        <div>
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400 dark:text-content-dark/55">
            Energía Generada por Fuente
          </p>
          <p className="mt-1 text-2xl font-black tracking-[-0.03em] text-[#193126] dark:text-content-dark lg:text-[1.55rem]">
            {formatKwh(total)}
          </p>
          <p className="mt-1 text-[11px] leading-4 text-slate-500 dark:text-content-dark/60 lg:hidden">Producción de energía evaluada en la ventana operativa actual.</p>
        </div>
        <SimulationStatusBadge className="rounded-full px-3 py-1.5" icon={<span className="material-symbols-outlined text-base">trending_up</span>}>
          +10%
        </SimulationStatusBadge>
      </div>
      <div className="min-h-[116px] flex-1 lg:min-h-[162px]" role="img" aria-label="Energy generated by source">
        <Bar data={chartData} options={options as never} />
      </div>
    </SimulationCard>
  )
}
