import { render, screen } from '@testing-library/react'
import { EnergyBarChart } from './EnergyBarChart'
import { ENERGY_BY_SOURCE } from '../data/dashboardMock'

describe('EnergyBarChart', () => {
  it('renders the energy chart region', () => {
    render(<EnergyBarChart data={ENERGY_BY_SOURCE} />)
    expect(screen.getByRole('img', { name: /energy generated by source/i })).toBeInTheDocument()
  })

  it('has an accessible label for screen readers', () => {
    render(<EnergyBarChart data={ENERGY_BY_SOURCE} />)
    expect(
      screen.getByRole('img', { name: /energy generated by source/i }),
    ).toBeInTheDocument()
  })

  it('renders the section title', () => {
    render(<EnergyBarChart data={ENERGY_BY_SOURCE} />)
    expect(screen.getByText('Energía Generada por Fuente')).toBeInTheDocument()
  })

  it('shows the total kWh', () => {
    render(<EnergyBarChart data={ENERGY_BY_SOURCE} />)
    // sum: 4000 + 3000 + 5000 + 8000 = 20000
    expect(screen.getByText(/20[.,]000 kWh/)).toBeInTheDocument()
  })

  it('shows the dominant source summary', () => {
    render(<EnergyBarChart data={ENERGY_BY_SOURCE} />)
    expect(screen.getByText(/Fuente dominante: Biomasa\./)).toBeInTheDocument()
  })
})
