import type { EnergySource } from '../services/dashboardTypes'
import { formatKwh, formatKwhAxisTick } from '../services/dashboardFormatters'
import { SimulationCard, SimulationStatusBadge } from '@/shared/components'

interface EnergyBarChartProps {
  data: EnergySource[]
}

export function EnergyBarChart({ data }: EnergyBarChartProps) {
  const total = data.reduce((sum, s) => sum + s.kwh, 0)
  const topSource = data.reduce<EnergySource | null>((leader, item) => {
    if (!leader || item.kwh > leader.kwh) return item
    return leader
  }, null)
  const maxValue = data.reduce((max, item) => Math.max(max, item.kwh), 0)

  return (
    <SimulationCard className="flex h-full min-h-[300px] flex-col rounded-sm">
      <div className="mb-2 flex items-start justify-between gap-4">
        <div>
          <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-600 dark:text-content-dark/78">
            Energía Generada por Fuente
          </p>
          <p className="mt-1 text-[1.9rem] font-black tracking-[-0.03em] text-[#193126] dark:text-content-dark lg:text-[1.45rem]">
            {formatKwh(total)}
          </p>
          <p className="mt-1 text-[11px] leading-4 text-slate-600 dark:text-content-dark/72">
            {topSource ? `Fuente dominante: ${topSource.label}.` : 'Producción de energía evaluada en la ventana operativa actual.'}
          </p>
        </div>
        {data.length > 0 ? null : (
          <SimulationStatusBadge className="rounded-full px-3 py-1.5">
            Sin datos
          </SimulationStatusBadge>
        )}
      </div>
      {data.length > 0 ? (
        <div className="flex h-full flex-col pt-3" role="img" aria-label="Energy generated by source">
          <div className="space-y-3">
            {data.map((item) => {
              const width = maxValue > 0 ? `${Math.max((item.kwh / maxValue) * 100, 4)}%` : '0%'

              return (
                <div key={item.label} className="grid grid-cols-[88px_minmax(0,1fr)_88px] items-center gap-3">
                  <span className="truncate text-sm font-medium text-slate-700 dark:text-content-dark/78">{item.label}</span>
                  <div className="h-5 rounded-full bg-[#edf3ec] px-1 py-1 dark:bg-white/[0.05]">
                    <div className="h-full rounded-full bg-[var(--chart-3)]" style={{ width }} />
                  </div>
                  <span className="text-right text-sm font-semibold text-[#1c2a22] dark:text-content-dark">{formatKwh(item.kwh)}</span>
                </div>
              )
            })}

            <div className="mt-auto flex justify-end pt-1 text-[11px] text-slate-600 dark:text-content-dark/72">
              <span>Escala máxima: {formatKwhAxisTick(maxValue)}</span>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex min-h-[120px] flex-1 items-center justify-center text-sm text-slate-500 dark:text-content-dark/60">
          El backend todavIa no enviO energIa agregada por fuente.
        </div>
      )}
    </SimulationCard>
  )
}
